import { StyleSheet } from 'react-native';

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.backgroundSecondary,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      backgroundColor: theme.colors.surface,
      borderBottomColor: theme.colors.borderLight,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    endButton: {
      color: theme.colors.error,
      fontSize: 16,
      fontWeight: '600',
    },
    placeholderWidth: {
      width: 60,
    },
    timerSection: {
      backgroundColor: theme.colors.surface,
      padding: 20,
      alignItems: 'center',
      marginBottom: 10,
    },
    timerLabel: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 5,
    },
    timerText: {
      fontSize: 36,
      fontWeight: 'bold',
      color: theme.colors.primary,
      marginBottom: 15,
    },
    pauseButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
    },
    pauseButtonText: {
      color: theme.colors.textInverse,
      fontSize: 14,
      fontWeight: '600',
      marginLeft: 5,
    },
    restTimerSection: {
      backgroundColor: theme.colors.warning,
      padding: 15,
      alignItems: 'center',
      marginBottom: 10,
    },
    restTimerLabel: {
      fontSize: 12,
      color: theme.colors.textInverse,
      marginBottom: 5,
    },
    restTimerText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.colors.textInverse,
      marginBottom: 10,
    },
    skipRestButton: {
      backgroundColor: theme.colors.overlayLight,
      paddingHorizontal: 15,
      paddingVertical: 6,
      borderRadius: 15,
    },
    skipRestText: {
      color: theme.colors.textInverse,
      fontSize: 12,
      fontWeight: '600',
    },
    content: {
      flex: 1,
    },
    exercisesSection: {
      backgroundColor: theme.colors.surface,
      padding: 20,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
    },
    addButtonText: {
      color: theme.colors.textInverse,
      fontSize: 12,
      fontWeight: '600',
      marginLeft: 4,
    },
    exerciseSection: {
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.borderLight,
      paddingBottom: 15,
    },
    exerciseHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    exerciseTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      flex: 1,
    },
    exerciseActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 15,
    },
    addSetButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    addSetText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '500',
      marginLeft: 2,
    },
    setItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 15,
      backgroundColor: theme.colors.backgroundSecondary,
      borderRadius: 8,
      marginBottom: 5,
    },
    setInfo: {
      flex: 1,
    },
    setNumber: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginBottom: 2,
    },
    setDetails: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.textPrimary,
    },
    setNotes: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    setActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    completeButton: {
      backgroundColor: theme.colors.success,
      padding: 8,
      borderRadius: 15,
    },
    completedIndicator: {
      padding: 4,
    },
    deleteButton: {
      padding: 4,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyText: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      marginBottom: 5,
    },
    emptySubtext: {
      fontSize: 14,
      color: theme.colors.textTertiary,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: theme.colors.backgroundSecondary,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.borderLight,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    cancelButton: {
      fontSize: 16,
      color: theme.colors.error,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      margin: 15,
      paddingHorizontal: 15,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 16,
    },
    exerciseList: {
      flex: 1,
    },
    exerciseItem: {
      backgroundColor: theme.colors.surface,
      padding: 15,
      marginHorizontal: 15,
      marginBottom: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
    },
    exerciseName: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      marginBottom: 4,
    },
    exerciseMuscle: {
      fontSize: 14,
      color: theme.colors.primary,
      marginBottom: 2,
    },
    exerciseEquipment: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    setModalContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 20,
      width: 400,
      maxWidth: 400,
    },
    setModalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      marginBottom: 20,
      textAlign: 'center',
    },
    inputRow: {
      flexDirection: 'row',
      gap: 15,
      marginBottom: 15,
    },
    inputGroup: {
      flex: 1,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.textPrimary,
      marginBottom: 5,
    },
    input: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: theme.colors.backgroundSecondary,
    },
    notesInput: {
      height: 60,
      textAlignVertical: 'top',
    },
    modalActions: {
      flexDirection: 'row',
      gap: 15,
      marginTop: 20,
    },
    modalCancelButton: {
      flex: 1,
      padding: 15,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
    },
    modalCancelText: {
      fontSize: 16,
      color: theme.colors.textSecondary,
    },
    modalAddButton: {
      flex: 1,
      padding: 15,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
    },
    modalAddText: {
      fontSize: 16,
      color: theme.colors.textInverse,
      fontWeight: '600',
    },
  });
